# setup-backend.ps1
#
# PowerShell equivalent of setup-backend.sh — bootstraps the Terraform
# remote state backend FOR ONE ENVIRONMENT on Windows without needing
# Git Bash or WSL.
#
# Creates a versioned, encrypted, private S3 bucket (shared across envs),
# then writes ..\envs\<env>\backend.tf with the real bucket/region/key.
#
# Usage:
#   .\setup-backend.ps1                                # env=develop, region=eu-west-1
#   .\setup-backend.ps1 -Env prod
#   .\setup-backend.ps1 -Env staging -Region us-east-1

param(
    [string]$Env    = "develop",
    [string]$Region = "eu-west-1"
)

$ErrorActionPreference = "Stop"

# Robust path resolution — works regardless of where the user invokes from.
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$EnvDir    = Join-Path $ScriptDir "..\envs\$Env"
$BackendTf = Join-Path $EnvDir "backend.tf"

# Sanity check the env folder. Catches typos like -Env prdo before we
# create stray files in non-existent directories.
if (-not (Test-Path $EnvDir)) {
    Write-Host "ERROR: env folder not found: $EnvDir"
    Write-Host "Create envs\$Env\ first, or pass an existing env via -Env NAME."
    exit 1
}

# Bucket name = project + account ID (shared across envs).
# S3 names are globally unique; the account ID guarantees no collisions
# with other AWS users.
$AccountId = (aws sts get-caller-identity --query Account --output text)
$Bucket    = "music-streaming-tfstate-$AccountId"
$StateKey  = "etl/music-streaming/$Env/terraform.tfstate"

Write-Host "========================================================"
Write-Host "  Music Streaming ETL — Backend Setup"
Write-Host "  Account : $AccountId"
Write-Host "  Env     : $Env"
Write-Host "  Bucket  : $Bucket"
Write-Host "  Region  : $Region"
Write-Host "  Key     : $StateKey"
Write-Host "========================================================"

# ── S3 Bucket ────────────────────────────────────────────────────────────────
# head-bucket exits non-zero when the bucket is missing OR not ours. We
# only branch on the success path; any error surfaces normally.
$bucketExists = $false
try {
    aws s3api head-bucket --bucket $Bucket --region $Region 2>$null
    if ($LASTEXITCODE -eq 0) { $bucketExists = $true }
} catch {
    $bucketExists = $false
}

if ($bucketExists) {
    Write-Host "[SKIP] Bucket $Bucket already exists (shared across envs)."
} else {
    Write-Host "[CREATE] Creating S3 bucket..."

    # us-east-1 is the AWS default and the API rejects a LocationConstraint
    # for it. Every other region requires the constraint.
    if ($Region -eq "us-east-1") {
        aws s3api create-bucket --bucket $Bucket --region $Region
    } else {
        aws s3api create-bucket `
            --bucket $Bucket `
            --region $Region `
            --create-bucket-configuration LocationConstraint=$Region
    }

    # Versioning — cheap insurance against accidental state overwrites.
    aws s3api put-bucket-versioning `
        --bucket $Bucket `
        --versioning-configuration Status=Enabled

    # Encryption at rest. New buckets default to this since 2023; making
    # it explicit signals intent to auditors and code reviewers.
    aws s3api put-bucket-encryption `
        --bucket $Bucket `
        --server-side-encryption-configuration '{\"Rules\":[{\"ApplyServerSideEncryptionByDefault\":{\"SSEAlgorithm\":\"AES256\"}}]}'

    # Public access block — Terraform state may contain secrets. NEVER
    # leave this bucket reachable from the public internet.
    aws s3api put-public-access-block `
        --bucket $Bucket `
        --public-access-block-configuration "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"

    Write-Host "[OK] Bucket $Bucket created with versioning, encryption, and public-access block."
}

# ── Write envs\<env>\backend.tf ──────────────────────────────────────────────
# Overwrite the file every run — idempotent and free of fragile
# placeholder-patching with sed/regex.
Write-Host "[WRITE] Generating $BackendTf..."

$BackendContent = @"
###############################################################################
# backend.tf — Remote state configuration ($Env)
#
# This file is GENERATED by scripts/setup-backend.ps1. Do not edit by hand —
# re-run the script if you need to change region / bucket / key.
#
# To tear down the remote backend for this env, run:
#   scripts/teardown-backend.ps1 -Env $Env
###############################################################################

terraform {
  backend "s3" {
    bucket       = "$Bucket"
    key          = "$StateKey"
    region       = "$Region"
    encrypt      = true
    use_lockfile = true
  }
}
"@

Set-Content -Path $BackendTf -Value $BackendContent -Encoding UTF8

Write-Host "[OK] backend.tf written for env=$Env."
Write-Host ""
Write-Host "========================================================"
Write-Host "  Backend ready. Next steps:"
Write-Host "    cd $EnvDir"
Write-Host "    terraform init -migrate-state    # first time, if you had local state"
Write-Host "    terraform apply"
Write-Host "========================================================"
