#!/usr/bin/env bash
set -euo pipefail

# setup-backend.sh
#
# Bootstraps the remote Terraform backend for one environment of the
# Music Streaming ETL pipeline. Creates a versioned, encrypted, private
# S3 bucket to hold Terraform state, then writes ../envs/<env>/backend.tf
# so `terraform init` from that env folder picks up the remote state.
#
# Why one bucket, many keys: a single state bucket is shared across all
# environments (develop / staging / prod). Each env gets its own KEY
# inside that bucket — e.g.
#     etl/music-streaming/develop/terraform.tfstate
#     etl/music-streaming/prod/terraform.tfstate
# State files are fully isolated per env even though they share storage.
#
# Native S3 locking (use_lockfile = true) is used — no DynamoDB needed.
#
# Usage:
#   ./setup-backend.sh                            # defaults: env=develop, region=eu-west-1
#   ./setup-backend.sh --env=prod
#   ./setup-backend.sh --env=staging --region=us-east-1

ENV="develop"
REGION="eu-west-1"

# Parse simple --key=value style flags.
for arg in "$@"; do
  case $arg in
    --env=*)    ENV="${arg#*=}" ;;
    --region=*) REGION="${arg#*=}" ;;
  esac
done

# Resolve script directory robustly — works no matter where the user
# invokes the script from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_TF="${SCRIPT_DIR}/../envs/${ENV}/backend.tf"

# Sanity check: the env folder must exist. If the user typoed --env=prdo,
# we'd otherwise create a stray file in a non-existent directory.
if [ ! -d "${SCRIPT_DIR}/../envs/${ENV}" ]; then
  echo "ERROR: env folder not found: ${SCRIPT_DIR}/../envs/${ENV}"
  echo "Create envs/${ENV}/ first, or pass an existing env via --env=NAME."
  exit 1
fi

# Bucket = project + account ID, SHARED across envs.
# S3 names are globally unique; embedding the account ID guarantees no
# collisions with other AWS users.
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
BUCKET="music-streaming-tfstate-${ACCOUNT_ID}"
STATE_KEY="etl/music-streaming/${ENV}/terraform.tfstate"

echo "========================================================"
echo "  Music Streaming ETL — Backend Setup"
echo "  Account : ${ACCOUNT_ID}"
echo "  Env     : ${ENV}"
echo "  Bucket  : ${BUCKET}"
echo "  Region  : ${REGION}"
echo "  Key     : ${STATE_KEY}"
echo "========================================================"

# ── S3 Bucket ────────────────────────────────────────────────────────────────
# head-bucket exits non-zero when the bucket is missing OR not ours. We
# only branch on success; the second case will surface as a normal error
# in a subsequent step.
if aws s3api head-bucket --bucket "${BUCKET}" --region "${REGION}" 2>/dev/null; then
  echo "[SKIP] Bucket ${BUCKET} already exists (shared across envs)."
else
  echo "[CREATE] Creating S3 bucket..."

  # us-east-1 is the AWS default and the API rejects a LocationConstraint
  # for it. Every other region requires the constraint. Handle both.
  if [ "${REGION}" = "us-east-1" ]; then
    aws s3api create-bucket --bucket "${BUCKET}" --region "${REGION}"
  else
    aws s3api create-bucket \
      --bucket "${BUCKET}" \
      --region "${REGION}" \
      --create-bucket-configuration LocationConstraint="${REGION}"
  fi

  # Versioning — cheap insurance against accidental state overwrites or
  # corruption. Terraform state is precious; treat it that way.
  aws s3api put-bucket-versioning \
    --bucket "${BUCKET}" \
    --versioning-configuration Status=Enabled

  # Encryption at rest. New buckets default to this since 2023; the
  # explicit call makes the intent obvious to anyone reading the script.
  aws s3api put-bucket-encryption \
    --bucket "${BUCKET}" \
    --server-side-encryption-configuration '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'

  # Public access block — Terraform state can contain secrets. It must
  # NEVER be publicly reachable.
  aws s3api put-public-access-block \
    --bucket "${BUCKET}" \
    --public-access-block-configuration "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"

  echo "[OK] Bucket ${BUCKET} created with versioning, encryption, and public-access block."
fi

# ── Write envs/<env>/backend.tf ──────────────────────────────────────────────
# Overwrite the file every run. Idempotent and free of fragile
# placeholder-patching with sed/regex.
echo "[WRITE] Generating ${BACKEND_TF}..."

cat > "${BACKEND_TF}" <<EOF
###############################################################################
# backend.tf — Remote state configuration (${ENV})
#
# This file is GENERATED by scripts/setup-backend.sh. Do not edit by hand —
# re-run the script if you need to change region / bucket / key.
#
# To tear down the remote backend for this env, run:
#   scripts/teardown-backend.sh --env=${ENV}
###############################################################################

terraform {
  backend "s3" {
    bucket       = "${BUCKET}"
    key          = "${STATE_KEY}"
    region       = "${REGION}"
    encrypt      = true
    use_lockfile = true
  }
}
EOF

echo "[OK] backend.tf written for env=${ENV}."

echo ""
echo "========================================================"
echo "  Backend ready. Next steps:"
echo "    cd $(dirname "${SCRIPT_DIR}")/envs/${ENV}"
echo "    terraform init -migrate-state    # first time, if you had local state"
echo "    terraform apply"
echo "========================================================"
