###############################################################################
# backend.tf — Remote state configuration (develop)
#
# This file is GENERATED by scripts/setup-backend.sh. Do not edit by hand —
# re-run the script if you need to change region / bucket / key.
#
# To tear down the remote backend for this env, run:
#   scripts/teardown-backend.sh --env=develop
###############################################################################

terraform {
  backend "s3" {
    bucket       = "music-streaming-tfstate-884596874091"
    key          = "etl/music-streaming/develop/terraform.tfstate"
    region       = "eu-west-1"
    encrypt      = true
    use_lockfile = true
  }
}
